# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDAyMjI4M2E0NzMxMmY4YTU0OGNkODE4MzEwNmEwY2YxMDE2NmM1ZmU5NmVhMGJkOWRiNTRiYTJiNGNiMGY1NmIyYzY2MTAyMDdmY2RkOTJjYTFhMzRiYjRmMjI3ZGY4NTQyZGNkZDUxYTdjYmUwNTNjYzZmY2Q0N2NmNDY2ZDg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
